@01_create.table.ZL_STB_MODEL.sql
@01_create.trigger.trg_zl_stb_model.sql
@01_create.trigger.trg_zl_user_group.sql
@02_alter.table.ZL_AREA.add.area_level.sql
@02_alter.table.ZL_CONT_APPSTORE.modify.DOWNLOAD_URL.VARCHAR2_1024.sql
@02_alter.table.zl_menu.add.Usergroup_ids_mac.sql
@02_alter.table.zl_software_version.add.Usergroup_ids_mac.sql
@02_alter.table.zl_user_group.add.ids_value.sql
@02_alter.table.zl_user_group.modify.name.VARCHAR2_50.sql
@02_update.table.zl_cont.modify_time_as_create_time.sql
@03_insert.into.zl_status_dict.ZL_CONT.TYPE.17.sql
@03_insert.into.zl_status_dict.ZL_USER_GROUP.TYPE.model.sql
@03_insert.into.ZL_STB_MODEL.sql
@11_create.or.replace.view.v_base_checkupdate_client.sql
@11_create.or.replace.view.v_base_menu_client.sql
@11_create.or.replace.view.v_checkupdate_client.sql
@11_create.or.replace.view.v_getappdownloadurl_client.sql
@11_create.or.replace.view.v_getarealist_client.sql