@01_create.table.zl_cont_sales.sql
@01_create.table.zl_sales_pay_type.sql
@01_create.trigger.trg_zl_cont_video_file.sql
@01_create.trigger.trg_zl_sales_pay_type.sql
@02_alter.table.zl_cont_sales.add.sales_no.sql
@02_alter.table.ZL_CONT_VIDEO.add.is_autoplay.NUMBER.sql
@02_alter.table.ZL_CONT_VIDEO.drop.IS_AUTOPLAY.sql
@02_alter.table.ZL_MENU.add.is_autoplay.NUMBER.sql
@02_alter.table.zl_sales_pay_type.add.name.sql
@03_insert.into.zl_menu.about.sql
@03_insert.into.ZL_MODULES.clearMemCache.sql
@03_insert.into.ZL_MODULES.contSales.sql
@03_insert.into.ZL_MODULES.contSalesPayType.sql
@03_insert.into.zl_status_dict.ZL_CONT.TYPE.16.sql
@03_insert.into.zl_status_dict.ZL_CONT_VIDEO_FILE.RATE_TAG.sql
@03_insert.into.zl_status_dict.ZL_SALES_PAY_TYPE.PAY_TYPE.sql
@03_insert.into.zl_status_dict.ZL_USER_GROUP.TYPE.zone.sql
@11_create.or.replace.view.v_base_checkupdate_client.sql
@11_create.or.replace.view.v_base_content_client.sql
@11_create.or.replace.view.v_base_menu_client.sql
@11_create.or.replace.view.v_checkupdate_client.sql
@11_create.or.replace.view.v_getappdetail_clientnt.sql
@11_create.or.replace.view.v_getcontentdetail_client.sql
@11_create.or.replace.view.v_getcontentlist_client.sql
@11_create.or.replace.view.v_searchcontentlist_client.sql