@01_create.table.ZL_CONT_CHANNEL.sql
@01_create.table.zl_cont_sales_hotinfo.sql
@01_create.table.ZL_CONT_SHOP.sql
@01_create.trigger.trg_zl_cont_channel.sql
@01_create.trigger.trg_zl_cont_sales_hotinfo.sql
@01_create.trigger.trg_zl_cont_shop.sql
@02_alter.table.comment.ZL_IMG.IS_URL_USED.sql
@02_alter.table.comment.ZL_MENU.IS_SHORTCUT.sql
@02_alter.table.reconstruct.zl_hotwords.sql
@02_alter.table.ZL_APP_DOWNLOAD_LOG.add.channel.sql
@02_alter.table.ZL_CONT.add.USERGROUP_IDS_MAC.zone.model.channel.sql
@02_alter.table.ZL_CONT.add.video_seg_time.sql
@02_alter.table.zl_cont_provider.add.icon_url.hot_info.sql
@02_alter.table.ZL_CONT_PROVIDER.add.PAY_TYPE_IDS.sql
@02_alter.table.ZL_CONT_SALES.add.gift.SUM_SALE.post_desc.service_desc.sql
@02_alter.table.ZL_CONT_SALES.add.sum_stock.sql
@02_alter.table.zl_cont_video_file.add.title.sql
@02_alter.table.ZL_MENU.add.USERGROUP_IDS_channel.sql
@02_alter.table.ZL_RELA_MENU_CONT.add.locked.sql
@02_alter.table.ZL_ROLES.add.menu_IDS.group_IDS.sql
@02_alter.table.ZL_SALES_PAY_TYPE.add.icon_url.sql
@02_alter.table.zl_software_version.add.Usergroup_ids_channel.sql
@02_alter.table.ZL_USER.add.channel.sql
@02_create.index.ZL_IMG.IDX_ZL_IMG_TID.sql
@03_insert.into.zl_cont_channel.sql
@03_insert.into.zl_cont_provider.zhuanbao-tianmao-taobao.sql
@03_insert.into.ZL_MODULES.channel.sql
@03_insert.into.ZL_MODULES.computeSandTowerUrl.sql
@03_insert.into.ZL_MODULES.shop.sql
@03_insert.into.zl_status_dict.ZL_CONT_CHANNEL.TYPE.APK.sql
@03_insert.into.zl_status_dict.ZL_MENU.IS_SHORTCUT.3.sql
@03_insert.into.zl_status_dict.ZL_SALES_PAY_TYPE.PAY_TYPE.3.sql
@03_insert.into.zl_status_dict.ZL_USER_GROUP.TYPE.channel.sql
@04_update.table.ZL_CONT.null_modify_time_to_create_time.sql
@04_update.table.ZL_CONT_SALES.url.from.alias.sql
@11_create.or.replace.function.as_provider.sql
@11_create.or.replace.function.check_black_gids.sql
@11_create.or.replace.function.check_user_gids.sql
@11_create.or.replace.trigger.trg_zl_cont.sql
@11_create.or.replace.view.v_base_content_client.sql
@11_create.or.replace.view.v_base_menu_client.sql
@11_create.or.replace.view.v_getcontentdetail_client.sql
@11_create.or.replace.view.v_getcontentlist_client.sql
@11_create.or.replace.view.v_getmenu_client.sql
@11_create.or.replace.view.v_getsalesdetail_client.sql
@11_create.or.replace.view.v_searchcontentlist_client.sql
@11_create.or.replace.v_base_checkupdate_client.sql
@11_create.or.replace.v_checkupdate_client.sql